import { PublicSessionView } from '../../types/practice';

export const DEFAULT_BINOMIAL_SESSION: PublicSessionView = {
  id: 'drill_local_binomial_fair_coin_exactly_two',
  template_id: 'binomial_fair_coin_exactly_two',
  revision: 1,
  title: 'Exactly two heads in four tosses',
  scenario_markdown: 'A fair coin is tossed four times independently. Find the probability of getting exactly two heads.',
  parameters: { n: 4, p: 0.5, k: 2 },
  assumptions: [
    'Four fixed trials',
    'Independent tosses',
    'Two outcomes per toss',
    'Constant head probability 0.5',
  ],
  current_stage_index: 0,
  completed: false,
  stages: [
    {
      id: 'define_variable',
      number: 1,
      label: 'Target',
      kind: 'choice',
      prompt_markdown: 'What should $X$ represent?',
      status: 'active',
      options: [
        { id: 'count_heads', text_markdown: 'The number of heads in four tosses' },
        { id: 'chance_one_head', text_markdown: 'The probability of a head on one toss' },
        { id: 'number_tosses', text_markdown: 'The number of tosses' },
      ],
      attempt_count: 0,
      max_attempts: 2,
      solved_on_retry: false,
      revealed: false,
      attempts: [],
    },
    {
      id: 'choose_model',
      number: 2,
      label: 'Model',
      kind: 'choice',
      prompt_markdown: 'Which distribution models this count?',
      status: 'unvisited',
      options: [
        { id: 'binomial', text_markdown: 'Binomial' },
        { id: 'poisson', text_markdown: 'Poisson' },
        { id: 'normal', text_markdown: 'Continuous normal' },
      ],
      attempt_count: 0,
      max_attempts: 2,
      solved_on_retry: false,
      revealed: false,
      attempts: [],
    },
    {
      id: 'check_parameters',
      number: 3,
      label: 'Conditions',
      kind: 'choice',
      prompt_markdown: 'Which parameter/condition statement fits?',
      status: 'unvisited',
      options: [
        { id: 'n4_p_half', text_markdown: '$n=4$, $p=0.5$, with independent tosses and constant success probability' },
        { id: 'n2_p_half', text_markdown: '$n=2$, $p=0.5$, because two heads are requested' },
        { id: 'n4_p2', text_markdown: '$n=4$, $p=2$, because two heads are requested' },
      ],
      attempt_count: 0,
      max_attempts: 2,
      solved_on_retry: false,
      revealed: false,
      attempts: [],
    },
    {
      id: 'translate_event',
      number: 4,
      label: 'Event',
      kind: 'choice',
      prompt_markdown: 'Which event means exactly two heads?',
      status: 'unvisited',
      options: [
        { id: 'equal_two', text_markdown: '$X=2$' },
        { id: 'at_most_two', text_markdown: '$X\\leq 2$' },
        { id: 'at_least_two', text_markdown: '$X\\geq 2$' },
      ],
      attempt_count: 0,
      max_attempts: 2,
      solved_on_retry: false,
      revealed: false,
      attempts: [],
    },
    {
      id: 'build_expression',
      number: 5,
      label: 'Expression',
      kind: 'choice',
      prompt_markdown: 'Which expression includes all possible orders of the two heads?',
      status: 'unvisited',
      options: [
        { id: 'with_combination', text_markdown: '$\\binom{4}{2}(0.5)^2(0.5)^2$' },
        { id: 'one_order_only', text_markdown: '$(0.5)^2(0.5)^2$' },
        { id: 'heads_only', text_markdown: '$\\binom{4}{2}(0.5)^2$' },
      ],
      attempt_count: 0,
      max_attempts: 2,
      solved_on_retry: false,
      revealed: false,
      attempts: [],
    },
    {
      id: 'calculate_probability',
      number: 6,
      label: 'Calculate',
      kind: 'numeric',
      prompt_markdown: 'Calculate $P(X=2)$. Enter a decimal, explicit percent, or fraction; no specific rounding is required.',
      status: 'unvisited',
      options: [],
      numeric_policy: {
        version: 1,
        allowed_forms: ['decimal', 'percent', 'fraction'],
      },
      attempt_count: 0,
      max_attempts: 2,
      solved_on_retry: false,
      revealed: false,
      attempts: [],
    },
    {
      id: 'interpret_probability',
      number: 7,
      label: 'Interpret',
      kind: 'choice',
      prompt_markdown: 'What does this probability describe?',
      status: 'unvisited',
      options: [
        { id: 'whole_experiment', text_markdown: 'The chance that a four-toss experiment produces exactly two heads' },
        { id: 'single_toss', text_markdown: 'The chance of heads on each individual toss' },
        { id: 'guaranteed_outcome', text_markdown: 'A guarantee that the next four tosses will produce two heads' },
      ],
      attempt_count: 0,
      max_attempts: 2,
      solved_on_retry: false,
      revealed: false,
      attempts: [],
    },
  ],
  updated_at: new Date().toISOString(),
};
